In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
headers={'User-Agent':'Mozilla/5.0(Windows NT 6.3;Win64;x64)AppleWebKit/537.36(KHTML,like Gecko)Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

In [ ]:
soup=BeautifulSoup(webpage,'lxml')
print(soup.prettify())

In [ ]:
soup.find_all('h1')[0].text

In [ ]:
for i in soup.find_all('h2',class_='companyCardWrapper__companyName'):
 print(i.text.strip())

In [68]:
 for i in soup.find_all('span',class_='companyCardWrapper__companyRatingValue'):
  print(i.text.strip())

3.8
4.1
3.9
3.8
4.0
3.9
3.9
3.9
3.7
4.0
3.7
3.8
3.9
4.1
4.2
4.0
4.0
4.0
3.9
3.6

In [90]:
for i in soup.find_all('h2',class_='companyCardWrapper__companyName'):
 print(i.text.strip())

TCS
Accenture
Cognizant
Wipro
ICICI Bank
HDFC Bank
Infosys
Capgemini
Tech Mahindra
Genpact
HCLTech
Axis Bank
Concentrix Corporation
IBM
Amazon
Reliance Jio
Larsen & Toubro Limited
HDB Financial Services
Reliance Retail
Teleperformance

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [ ]:
headers={'User-Agent':'Mozilla/5.0(Windows NT 6.3;Win64;x64)AppleWebKit/537.36(KHTML,like Gecko)Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

soup=BeautifulSoup(webpage,'lxml')

In [ ]:
company=soup.find_all('div', class_='companyCardWrapper')
company

In [ ]:
name=[]
ratings=[]
reviews=[]
jobs=[]


for i in company:
 
    
 name.append((i.find('h2')).text.strip())
 ratings.append(i.find('span',class_='companyCardWrapper__companyRatingValue').text.strip())
 reviews.append(i.find('a', class_='companyCardWrapper__ActionWrapper').text.strip())
 jobs.append(i.find('span',class_='companyCardWrapper__ActionTitle').text.strip())

In [80]:
name

['TCS',
 'Accenture',
 'Cognizant',
 'Wipro',
 'ICICI Bank',
 'HDFC Bank',
 'Infosys',
 'Capgemini',
 'Tech Mahindra',
 'Genpact',
 'HCLTech',
 'Axis Bank',
 'Concentrix Corporation',
 'IBM',
 'Amazon',
 'Reliance Jio',
 'Larsen & Toubro Limited',
 'HDB Financial Services',
 'Reliance Retail',
 'Teleperformance']

In [87]:
print(ratings,name)

['3.8', '4.1', '3.9', '3.8', '4.0', '3.9', '3.9', '3.9', '3.7', '4.0', '3.7', '3.8', '3.9', '4.1', '4.2', '4.0', '4.0', '4.0', '3.9', '3.6'] ['TCS', 'Accenture', 'Cognizant', 'Wipro', 'ICICI Bank', 'HDFC Bank', 'Infosys', 'Capgemini', 'Tech Mahindra', 'Genpact', 'HCLTech', 'Axis Bank', 'Concentrix Corporation', 'IBM', 'Amazon', 'Reliance Jio', 'Larsen & Toubro Limited', 'HDB Financial Services', 'Reliance Retail', 'Teleperformance']

In [88]:
ratings

['3.8',
 '4.1',
 '3.9',
 '3.8',
 '4.0',
 '3.9',
 '3.9',
 '3.9',
 '3.7',
 '4.0',
 '3.7',
 '3.8',
 '3.9',
 '4.1',
 '4.2',
 '4.0',
 '4.0',
 '4.0',
 '3.9',
 '3.6']

In [101]:
reviews

['61.9k Reviews',
 '39.5k Reviews',
 '36.1k Reviews',
 '29.6k Reviews',
 '29.3k Reviews',
 '28.7k Reviews',
 '27k Reviews',
 '25.1k Reviews',
 '23.6k Reviews',
 '22.8k Reviews',
 '22.7k Reviews',
 '19.3k Reviews',
 '18.1k Reviews',
 '17.5k Reviews',
 '17.4k Reviews',
 '17.4k Reviews',
 '16.5k Reviews',
 '15.5k Reviews',
 '15.2k Reviews',
 '14.6k Reviews']

In [108]:
company[0].find_all('span',class_='companyCardWrapper__interLinking')[0].text.strip()

'IT Services & Consulting | 1 Lakh+ Employees | Public | 55 years old | Mumbai +280 more'

In [112]:
company[0].find('span',class_='companyCardWrapper__ratingValues').text.strip()

'Job Security, Work Life Balance, Company Culture'

In [ ]:
jobs

In [9]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

headers={'User-Agent':'Mozilla/5.0(Windows NT 6.3;Win64;x64)AppleWebKit/537.36(KHTML,like Gecko)Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

soup=BeautifulSoup(webpage,'lxml')
company=soup.find_all('div', class_='companyCardWrapper')

name=[]
ratings=[]
reviews=[]



for i in company:
 
    
  name.append((i.find('h2')).text.strip())
  ratings.append(i.find('span',class_='companyCardWrapper__companyRatingValue').text.strip())
  reviews.append(i.find('a', class_='companyCardWrapper__ActionWrapper').text.strip())

In [2]:
name

['TCS',
 'Accenture',
 'Cognizant',
 'Wipro',
 'ICICI Bank',
 'HDFC Bank',
 'Infosys',
 'Capgemini',
 'Tech Mahindra',
 'Genpact',
 'HCLTech',
 'Axis Bank',
 'Concentrix Corporation',
 'IBM',
 'Amazon',
 'Reliance Jio',
 'Larsen & Toubro Limited',
 'HDB Financial Services',
 'Reliance Retail',
 'Teleperformance']

In [3]:
reviews

['61.9k Reviews',
 '39.5k Reviews',
 '36.1k Reviews',
 '29.7k Reviews',
 '29.3k Reviews',
 '28.7k Reviews',
 '27k Reviews',
 '25.1k Reviews',
 '23.6k Reviews',
 '22.8k Reviews',
 '22.7k Reviews',
 '19.4k Reviews',
 '18.1k Reviews',
 '17.5k Reviews',
 '17.5k Reviews',
 '17.4k Reviews',
 '16.5k Reviews',
 '15.5k Reviews',
 '15.2k Reviews',
 '14.6k Reviews']

In [10]:
ratings

['3.8',
 '4.1',
 '3.9',
 '3.8',
 '4.0',
 '3.9',
 '3.9',
 '3.9',
 '3.7',
 '4.0',
 '3.7',
 '3.8',
 '3.9',
 '4.1',
 '4.2',
 '4.0',
 '4.0',
 '4.0',
 '3.9',
 '3.6']

In [11]:
d={'name':name, 'ratings':ratings, 'reviews':reviews}
df=pd.DataFrame(d)
df

                       name ratings        reviews
0                       TCS     3.8  61.9k Reviews
1                 Accenture     4.1  39.5k Reviews
2                 Cognizant     3.9  36.1k Reviews
3                     Wipro     3.8  29.7k Reviews
4                ICICI Bank     4.0  29.3k Reviews
5                 HDFC Bank     3.9  28.7k Reviews
6                   Infosys     3.9    27k Reviews
7                 Capgemini     3.9  25.1k Reviews
8             Tech Mahindra     3.7  23.6k Reviews
9                   Genpact     4.0  22.8k Reviews
10                  HCLTech     3.7  22.7k Reviews
11                Axis Bank     3.8  19.4k Reviews
12   Concentrix Corporation     3.9  18.1k Reviews
13                      IBM     4.1  17.5k Reviews
14                   Amazon     4.2  17.5k Reviews
15             Reliance Jio     4.0  17.4k Reviews
16  Larsen & Toubro Limited     4.0  16.5k Reviews
17   HDB Financial Services     4.0  15.5k Reviews
18          Reliance Retail     3.9  15.2k Reviews
19          Teleperformance     3.6  14.6k Reviews

In [25]:
final=pd.DataFrame()

for j in range(1,4):

 headers={'User-Agent':'Mozilla/5.0(Windows NT 6.3;Win64;x64)AppleWebKit/537.36(KHTML,like Gecko)Chrome/80.0.3987.162 Safari/537.36'}
 webpage=requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

 soup=BeautifulSoup(webpage,'lxml')
    
 company=soup.find_all('div', class_='companyCardWrapper')

 name=[]
 ratings=[]
 reviews=[]



 for i in company:
 
    
  name.append((i.find('h2')).text.strip())
  ratings.append(i.find('span',class_='companyCardWrapper__companyRatingValue').text.strip())
  reviews.append(i.find('a', class_='companyCardWrapper__ActionWrapper').text.strip())

 d={'name':name, 'ratings':ratings, 'reviews':reviews}
 df=pd.DataFrame(d)
 final=final.append(df,ignore_index=True)

C:\Users\Dibyarchana Nayak\AppData\Local\Temp\ipykernel_7252\1042051908.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)
C:\Users\Dibyarchana Nayak\AppData\Local\Temp\ipykernel_7252\1042051908.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)
C:\Users\Dibyarchana Nayak\AppData\Local\Temp\ipykernel_7252\1042051908.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  final=final.append(df,ignore_index=True)

In [26]:
final

                       name ratings        reviews
0                       TCS     3.8  61.9k Reviews
1                 Accenture     4.1  39.5k Reviews
2                 Cognizant     3.9  36.1k Reviews
3                     Wipro     3.8  29.7k Reviews
4                ICICI Bank     4.0  29.3k Reviews
5                 HDFC Bank     3.9  28.7k Reviews
6                   Infosys     3.9    27k Reviews
7                 Capgemini     3.9  25.1k Reviews
8             Tech Mahindra     3.7  23.6k Reviews
9                   Genpact     4.0  22.8k Reviews
10                  HCLTech     3.7  22.7k Reviews
11                Axis Bank     3.8  19.4k Reviews
12   Concentrix Corporation     3.9  18.1k Reviews
13                      IBM     4.1  17.5k Reviews
14                   Amazon     4.2  17.5k Reviews
15             Reliance Jio     4.0  17.4k Reviews
16  Larsen & Toubro Limited     4.0  16.5k Reviews
17   HDB Financial Services     4.0  15.5k Reviews
18          Reliance Retail     3.9  15.2k Reviews
19          Teleperformance     3.6  14.6k Reviews
20                      TCS     3.8  61.9k Reviews
21                Accenture     4.1  39.5k Reviews
22                Cognizant     3.9  36.1k Reviews
23                    Wipro     3.8  29.7k Reviews
24               ICICI Bank     4.0  29.3k Reviews
25                HDFC Bank     3.9  28.7k Reviews
26                  Infosys     3.9    27k Reviews
27                Capgemini     3.9  25.1k Reviews
28            Tech Mahindra     3.7  23.6k Reviews
29                  Genpact     4.0  22.8k Reviews
30                  HCLTech     3.7  22.7k Reviews
31                Axis Bank     3.8  19.4k Reviews
32   Concentrix Corporation     3.9  18.1k Reviews
33                      IBM     4.1  17.5k Reviews
34                   Amazon     4.2  17.5k Reviews
35             Reliance Jio     4.0  17.4k Reviews
36  Larsen & Toubro Limited     4.0  16.5k Reviews
37   HDB Financial Services     4.0  15.5k Reviews
38          Reliance Retail     3.9  15.2k Reviews
39          Teleperformance     3.6  14.6k Reviews
40                      TCS     3.8  61.9k Reviews
41                Accenture     4.1  39.5k Reviews
42                Cognizant     3.9  36.1k Reviews
43                    Wipro     3.8  29.7k Reviews
44               ICICI Bank     4.0  29.3k Reviews
45                HDFC Bank     3.9  28.7k Reviews
46                  Infosys     3.9    27k Reviews
47                Capgemini     3.9  25.1k Reviews
48            Tech Mahindra     3.7  23.6k Reviews
49                  Genpact     4.0  22.8k Reviews
50                  HCLTech     3.7  22.7k Reviews
51                Axis Bank     3.8  19.4k Reviews
52   Concentrix Corporation     3.9  18.1k Reviews
53                      IBM     4.1  17.5k Reviews
54                   Amazon     4.2  17.5k Reviews
55             Reliance Jio     4.0  17.4k Reviews
56  Larsen & Toubro Limited     4.0  16.5k Reviews
57   HDB Financial Services     4.0  15.5k Reviews
58          Reliance Retail     3.9  15.2k Reviews
59          Teleperformance     3.6  14.6k Reviews

In [27]:
final.to_csv('companies dataset.csv')